# Clears the console before running
clear

#Gets the directory to search for the input files
search_dir="$PWD/inputs"


# Runs the unittests in the Tests Folder

echo "Running Unit Tests"
echo "=================="
python -m unittest

# Removes the previous outputs generated by the program
rm  "$PWD/actual_output/"*

# Creating a variable for incrementing and adding it to file name
let index=1
echo

# This part creates the output file using the touch command
# prints the contents of the program to the console
# and then pipes the stdout of the program to 
# actual_output/sample-output%.txt 
# (---> % means numbers are dynamically generated)


echo "=====Program Output======"
for i in "$search_dir"/*
do
    filename=$(basename "$i")
    read -d'-' -a filenamearray <<< "$filename"
    touch "$PWD/actual_output/${filenamearray}-output${index}.txt"
    savefile="$PWD/actual_output/${filenamearray}-output${index}.txt"
    let index=$index+1
    python -m geektrust $i | tee $savefile 
done
echo "==========END============"

echo
echo


# Runs the Integration Test in the tests folder
# to check if the generated outputs are the same
# as expected ouputs
echo "Running Integration Test"
echo "========================"
python -m unittest $PWD/tests/IntegrationTest.py
